### ISSUE TITLE
PHPCS not using WordPress.XSS.EscapeOutput.OutputNotEscaped

### ISSUE THREAD

**Issue by mattheu** [humanmade/coding-standards#102]
The following code should be an error. The WP coding standards include checks for unescaped output `WordPress.XSS.EscapeOutput.OutputNotEscaped`

```
echo $foo;
```

[But our coding standards are not flagging it - this rule is explicitly ignored](https://github.com/humanmade/coding-standards/blob/master/HM/ruleset.xml#L24)

Was this intentional?

**Comment by mikeselander** [comment]
@rmccue do you know why we're excluding `WordPress.Security.EscapeOutput`?

**Comment by rmccue** [comment]
Yeah, I don't remember why this existed. I think it may have been in conflict with another rule, and I used the one that was more specific, but unsure!

**Comment by mikeselander** [comment]
OK, perhaps we should add some test cases for escaping and try to add it back in? We definitely want to try and catch unescaped echoing imo.

**Comment by rmccue** [comment]
Makes a lot of sense 👍
