### ISSUE TITLE
Stylelint Moving Forward

### ISSUE THREAD

**Issue by mikeselander** [humanmade/coding-standards#107]
We've had a Stylelint config sitting in this repo for almost a year now, and it would be be most useful to our project to release this and get it into practice on projects. This is a rough plan of steps involved with getting Stylelint moved forward and into use on our projects.

As with everything, would love perspectives and to know if I've missed a step here.

 - [x] Complete carry-on rule adjustments (#103, #106) cc @peterwilsoncc 
 - [x] Add Lerna to repo
 - [x] Push Stylelint to npm as a standalone package, tagged 0.6
 - [x] Release 0.6 of full coding standards (we should focus on closing out open, completed PRs first)
 - [x] Include Stylint and any other carry-on changes as a 0.7 follow up to 0.6
 - [x] Write internal Dev post explaining Stylelint (what it is, how it works, how we'll release it)
 - [x] Add Stylelint to HM Linter (ref: https://github.com/humanmade/linter-bot/issues/80)

**Comment by kadamwhite** [comment]
@mikeselander is figuring out stylelint in linterbot, and has a draft post ready to go, so this is close!

**Comment by mikeselander** [comment]
Stylelint is available via our Linter Bot and I have an internal post scheduled for next week talking about setting up stylelint on projects. This is (finally) complete 🎉
