### ISSUE TITLE
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"

### ISSUE THREAD

**Issue by connerbw** [humanmade/coding-standards#110]
When using PHP 7.3 (and nightly builds) I am seeing:

```
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 1 | ERROR | An error occurred during processing; checking has been aborted. The
   |       | error message was: "continue" targeting switch is equivalent to "break".
   |       | Did you mean to use "continue 2"? in
   |       | /home/travis/build/[secure]/[secure]/vendor/squizlabs/php_codesniffer/src/Tokenizers/Tokenizer.php
   |       | on line 746 (Internal.Exception)
--------------------------------------------------------------------------------
```

This is supposed to be fixed in 3.3.1, see:

https://github.com/squizlabs/PHP_CodeSniffer/issues/2087

Is it possible to upgrade? See:

 + https://github.com/humanmade/coding-standards/blob/464d438c678367bc2b472f5798395867e8c8eb55/composer.json#L9
 + https://semver.mwl.be/#?package=squizlabs%2Fphp_codesniffer&version=~3.2.0&minimum-stability=stable

**Comment by mikeselander** [comment]
@connerbw we're working on upgrading PHPCS and this should be included in v0.6 when we release it.
