### ISSUE TITLE
Add Lerna for independent package management

### ISSUE THREAD

**Issue by mikeselander** [humanmade/coding-standards#115]
Now that we have both `eslint` and `stylelint` configurations for coding-standards, we need a tool to handle the separate NPM repos for both packages. 

We should add [Lerna](https://github.com/lerna/lerna#getting-started) to handle this.

**Comment by rmccue** [comment]
The main thing to ensure with this is that package versions for ESLint, Stylelint, and phpcs remain in lock-step with each other.

**Comment by ntwb** [comment]
> The main thing to ensure with this is that package versions for ESLint, Stylelint, and phpcs remain in lock-step with each other.

Oh, in #175 I made each package version "independent", I will update it so all packages use the same version number for each release
