### ISSUE TITLE
Consider relaxing the eslint "no-use-before-define" rule

### ISSUE THREAD

**Issue by goldenapples** [humanmade/coding-standards#118]
When working in projects with a lot of modular javascript functionality, I find it nice to follow roughly the same organization structure for javascript code as we do for namespaced PHP code, with each file handling a specific discrete bit of functionality, declaring imports at the top, defining a `bootstrap()` function which attaches any event listeners or hooks necessary, and then from there defining all the functions which will be attached on those event listeners.

In javascript, this ends up needing to be turned on its head, because referencing a function before it's been defined violates the eslint `no-use-before-define` rule.

Id like to be able to do something like this:

```
/* global definitions */

import something from 'something';

import somethingLocal from './something-local';

const buttons = document.querySelectorAll( 'button' );

export const bootstrap = () => {
    [ ...buttons ].forEach(
        btn => btn.addEventListener( 'click', onButtonClick )
    );

    window.addEventListener( "scroll", onScroll );
};

const onButtonClick = () => {};

const onScroll = () => {};

// (or for a more realistic example, this might be in another file which imports this)
document.addEventListener( 'DOMContentLoaded', bootstrap );
```

but because of the `no-use-before-define` rule, I have to put the `bootstrap()` function at the bottom of the file.

The [options available for this rule](https://github.com/eslint/eslint/blob/master/docs/rules/no-use-before-define.md) seem to allow using functions and variables before they're defined in top to bottom order as long as they're used in a safe way, for example inside of functions.

Has anyone else experienced this issue? I think it would be nice to change the rule in our coding standards to 

```
"no-use-before-define": ["error", { "functions": false, "variables": false }]
```

**Comment by pdewouters** [comment]
Can you override it in your own `eslintrc` config?

**Comment by kadamwhite** [comment]
@rmccue , @mikeselander and I discussed this today, and our recommendation is to control this in file-level config (or project, if necessary) rather than changing it in the standards
