### ISSUE TITLE
Update WPCS to 2.1.0

### ISSUE THREAD

**Issue by mikeselander** [humanmade/coding-standards#130]
We recently bumped WPCS to 1.2.1, but it took so long that they've now released a version 2.1.0. We should probably look at bumping that version up for our standards.

**Comment by ntwb** [comment]
FYI: WPCS 2.1 is planned for release April 8th

**Comment by mikeselander** [comment]
Thanks for the FYi @ntwb, updated 👍

**Comment by mikeselander** [comment]
Noting that VIPCS conflicts with WPCS 2.*, which would affect our ability to upgrade. It looks like the VIPCS team is working on compatibility but there's no promise when it would be ready: https://github.com/Automattic/VIP-Coding-Standards/milestone/4

**Comment by spacedmonkey** [comment]
At the same time as looking into this, you will likely need VIP-Coding-Standards to 1.0.0 . See #136

**Comment by spacedmonkey** [comment]
Any plans for this?

**Comment by mikeselander** [comment]
@spacedmonkey we will definitely upgrade to this at some point, but we're not in a rush here. These upgrades tend to break existing expectations on current projects so we take them pretty slowly. Additionally there is a dependency on VIPCS updating their code to work with 2.* of WPCS so we won't even consider this until that's fixed.

That being said, if someone else has the time to look into and consider regressions that might come from the 1.2 -> 2.1 upgrade we're always accepting PRs!

**Comment by spacedmonkey** [comment]
Now that VIP GO coding standard is compatible with VIP GO standard 2.0. These is no reason not to update them both.

**Comment by rmccue** [comment]
This will include https://github.com/WordPress/WordPress-Coding-Standards/pull/1684 too.

**Comment by ntwb** [comment]
I've updated #151 and it now passes with the latest release of WPCS & VIPCS
