### ISSUE TITLE
Add rule to block use of isset with multiple arguments

### ISSUE THREAD

**Issue by rmccue** [humanmade/coding-standards#142]
IMO, `isset( $a, $b )` is unclear, and there's no good reason to use it instead of the more explicit `isset( $a ) && isset( $b )`

Anyone have strong thoughts either way on this?

**Comment by pdewouters** [comment]
I don't see it used that often, I don't think most people even know you can do that. But I don't think it unclear.

**Comment by fklein-lu** [comment]
I do prefer the `isset( $a ) && isset( $b )` version, as it contains the logical operators, which `isset( $a, $b )` does not. Or said differently the first version is clear, even if your understanding of PHP is moderate, the second one requires you to understand what this particular function does in detail.

**Comment by tfrommen** [comment]
Closed as per https://github.com/humanmade/coding-standards/commit/6ad1fc9f5bd57b0f9fa2658e5e9134168fa9b60d.
