### ISSUE TITLE
Sniffs are not installed properly

### ISSUE THREAD

**Issue by pdewouters** [humanmade/coding-standards#152]
`composer.json`:
```
    "config": {
        "autoloader-suffix": "DontChange",
        "vendor-dir": "content/vendor"
    },
...
    "require-dev": {
        "humanmade/coding-standards": "^0.7",
        "phpunit/phpunit": "6.5"
    }
```

`composer update`: 

```
PHP CodeSniffer Config installed_paths set to ../../automattic/vipwpcs,../../humanmade/coding-standards,../../humanmade,../../wp-coding-standards/wpcs,../../phpcompatibility/php-compatibility,../../phpcompatibility/phpcompatibility-paragonie,../../phpcompatibility/phpcompatibility-wp,../../fig-r/psr2r-sniffer
```

Running the sniffs

` vendor/bin/phpcs --standard=humanmade/coding-standards themes/hoh-theme -s               ✔
ERROR: the "humanmade/coding-standards" coding standard is not installed. The installed coding standards are PEAR, Zend, PSR2, MySource, Squiz, PSR1, PSR12, WordPressVIPMinimum, WordPress-VIP-Go, coding-standards, coding-standards, WordPress-VIP, WordPress, WordPress-Extra, WordPress-Docs, WordPress-Core, PHPCompatibility, PHPCompatibilityParagonieRandomCompat, PHPCompatibilityParagonieSodiumCompat, PHPCompatibilityWP and PSR2R`

**Comment by pdewouters** [comment]
I think one issue is that both the WPCS and the HM standards end up as `coding-standards` so how do we know which one is run?

**Comment by pdewouters** [comment]
Closing, as I had to add a dependency to the dealerdirect package on my project `composer.json`

**Comment by rmccue** [comment]
Hmm, annoying, that shouldn't be required I think @mikeselander?

**Comment by mikeselander** [comment]
No, that definitely shouldn't be required...

**Comment by pdewouters** [comment]
have you noticed the double `coding-standards, coding-standards`

**Comment by pdewouters** [comment]
I think this was an issue specific to this project, so closing
