### ISSUE TITLE
PHPCS: Allow the use of `error_log()`

### ISSUE THREAD

**Issue by fklein-lu** [humanmade/coding-standards#162]
The WordPress Coding Standards includes a sniff that flags the use of the PHP `error_log()` function, see `WordPress.PHP.DevelopmentFunctions`.

While this makes sense for WordPress Core, it does not make sense for client projects. We should not only allow developers to use the `error_log()` function, but also encourage them to use error logging where it makes sense.

**Comment by rmccue** [comment]
I think we already override another part of this to allow `trigger_error()` which does roughly the same thing, so +1.

**Comment by kadamwhite** [comment]
This has been manually allowed in the HM minimum standard.

**Comment by kadamwhite** [comment]
Resolved in #180 :tada:
