### ISSUE TITLE
Migrate (and deprecate) `eslint-config-humanmade` to `@humanmade/eslint-config`

### ISSUE THREAD

**Issue by ntwb** [humanmade/coding-standards#176]
This issue is to discuss making migrating and deprecating the `eslint-config-humanmade` into a scoped _npm_ package `@humanmade/eslint-config`

> https://docs.npmjs.com/misc/scope
> All npm packages have a name. Some package names also have a scope. A scope follows the usual rules for package names (URL-safe characters, no leading dots or underscores). When used in package names, scopes are preceded by an @ symbol and followed by a slash, e.g.
>
> `@somescope/somepackagename`
>
> Scopes are a way of grouping related packages together, and also affect a few things about the way npm treats the package.
> 
> Each npm user/organization has their own scope, and only you can add packages in your scope. This means you don’t have to worry about someone taking your package name ahead of you. Thus it is also a good way to signal official packages for organizations.

Once migrated the package would live under the HM umbrella here:
> https://www.npmjs.com/org/humanmade

the stylelint package is already a scoped package under the `@humanmade` scope:
> https://www.npmjs.com/package/@humanmade/stylelint-config

the ESLint package would become:
> https://www.npmjs.com/package/@humanmade/eslint-config

the _old_ ESLint package would require deprecation 
> https://docs.npmjs.com/cli/deprecate

the _old_ ESLint package would continue to exist and would display a deprecation warning when installed and would include a link to the new scoped package:
https://www.npmjs.com/package/eslint-config-humanmade

**Comment by rmccue** [comment]
IIRC, it was named this way originally because there was an ESLint issue if you didn't have it prefixed with `eslint-config-`. Assuming that's probably been fixed by now though.

**Comment by kadamwhite** [comment]
From [ESLint's Shareable Configs guide](https://eslint.org/docs/developer-guide/shareable-configs):

> npm scoped modules are also supported in a number of ways.
>
> By using the module name:
>
> ```json
> {
>     "extends": "@scope/eslint-config"
> }
> ```
>
> You can also omit the eslint-config and it will be automatically assumed by ESLint:
>
> ```json
> {
>     "extends": "@scope"
> }
> ```
>
> The module name can also be customized, just note that when using scoped modules it is not possible to omit the `eslint-config-` prefix. Doing so would result in package naming conflicts, and thus in resolution errors in most of cases. For example a package named `@scope/eslint-config-myconfig` vs `@scope/my-config`, since both are valid scoped package names, the configuration should be specified as:
>
> ```json
> {
>     "extends": "@scope/eslint-config-myconfig"
> }
> ```

**Comment by kadamwhite** [comment]
Depends on #180 presumably; we should target this change for 1.0

**Comment by mikeselander** [comment]
Just to  clarify our understanding of the steps involved in this change, I wanted to outline the steps as I understand them so that any one of you has an opportunity to identify where I've gone wrong 😄

1. We publish a new package to NPM with the name of `@humanmade/eslint-config`, updating the `package.json` at the same time. This new package would only have the current version and future versions of coding-standards.
2. We deprecate `eslint-config-humanmade` with a message including a link to the new package

It seems to me that it would be best to do this right before we release version 1.0 to align with 1.0 being a breaking change.

Any issues or things I'm missing with the steps above?

**Comment by ntwb** [comment]
> Any issues or things I'm missing with the steps above?
No, that sounds right to me 👍🏼

**Comment by kadamwhite** [comment]
`@humanmade/eslint-config` exists! Enjoy responsibly!

We've marked `eslint-config-humanmade` as deprecated, with a note about the rename. Mike has also published an internal post with instructions about upgrading.

Closing this out as resolved; thank you @ntwb a million times over for driving this!
