### ISSUE TITLE
Add rule for JSX Boolean values

### ISSUE THREAD

**Issue by mattheu** [humanmade/coding-standards#182]
The following code

```js
<MyButton isPrimary={ true } />
```

can be simplified to the following, which I think is neater.

```js
<MyButton isPrimary />
```

Whilst my preference is for the shorter version, I wanted to open this up to to discussion. Do we have a preference on this? 

If we decide one way or the other, we could use the rule Eslint rule [`jsx-boolean-value`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md) to enforce it, or disallow it.

**Comment by rmccue** [comment]
I prefer it. I'd also rename it to just `primary`; `is` is a bit of Hungarian notation that's not super necessarily, since you don't specify the negative. eg:

```
<Button primary submit />
```

**Comment by mattheu** [comment]
Ah for some reason I thought we explicitly preferred this style of prop naming - but maybe that's just a preference in WordPress/Gutenberg.

**Comment by rmccue** [comment]
Only the `on` prefix for callbacks, specifically because they're a weird type of prop (kind of two-way); also follows React's general patterns.

**Comment by pdewouters** [comment]
I like the `is` and `has` prefixes, it tells me straight away that it's a boolean - `primary` could be a color value

**Comment by mikeselander** [comment]
I agree with Paul here - I quite like using `is` or `has` prefixes as it makes the prop usage crystal-clear. 

I'm in support of this change 👍
