### ISSUE TITLE
Standards not being detected by VS Code

### ISSUE THREAD

**Issue by johnbillion** [humanmade/coding-standards#184]
Given VS Code and the phpcs extension (either https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs or the https://marketplace.visualstudio.com/items?itemName=shevaua.phpcs fork), the HM ruleset does not appear to get detected at all. Swapping out the HM ruleset for the WordPress-Extra ruleset and changing nothing else, results in the sniffs working.

Here's an example repo: https://github.com/johnbillion/phpcstest

* Clone the above repo
* Run `composer install`
* Open the repo in VS Code
* Open index.php and observe that the standards violation on line 5 does not get detected
* Open phpcs.xml.dist, comment out the HM line, and uncomment the WordPress-Extra line, and observe that the standards violation will be correctly detected

The `Output` panel does not show any errors.

I have no global dependencies installed.

**Comment by johnbillion** [comment]
Note that running `./vendor/bin/phpcs .` on the CLI works as expected.

**Comment by ocean90** [comment]
I remember [something similar](https://github.com/wearerequired/coding-standards/issues/27) in our standard. Try removing [this](https://github.com/humanmade/coding-standards/blob/0fb7ee17abf804e5adb5a75ee3e71aff453232fa/HM/ruleset.xml#L5) and/or [this](https://github.com/humanmade/coding-standards/blob/0fb7ee17abf804e5adb5a75ee3e71aff453232fa/HM/ruleset.xml#L10) lines.

**Comment by mikeselander** [comment]
hhhmmmm That first line came up as an issue in #159 as well. I think it might be time to remove if it's indeed causing these issues as well.

**Comment by svandragt** [comment]
For future reference.
The workaround presented here breaks PHPStorm's autoconfiguration to run PHPCS as it cannot find WordPress-Extra sniffs. Changing it back to HM fixes that as well.
