### ISSUE TITLE
Increase PHP test version to 7.2

### ISSUE THREAD

**Issue by fklein-lu** [humanmade/coding-standards#186]
Our [Cloud infrastructure ](https://www.altis-dxp.com/resources/docs/cloud/specifications/) is running PHP 7.2, but the Coding Standards still set the test version to 7.1 (see https://github.com/humanmade/coding-standards/blob/master/HM/ruleset.xml#L16).

We should align this.

**Comment by rmccue** [comment]
Noted in #180 and will look to fix there.

**Comment by kadamwhite** [comment]
We're planning to remove the PHP version default or change it to something lower, but the Altis standard will specify a specific version that will sync with our infra.

**Comment by kadamwhite** [comment]
Per #191 we should remove the minimum version from all non-Altis rulesets.

**Comment by mikeselander** [comment]
Closing in lieu of #191 

@rmccue may include this in a separate Altis ruleset, but that will be a different issue.
