### ISSUE TITLE
Re-consider setting `testVersion` value by default

### ISSUE THREAD

**Issue by mikeselander** [humanmade/coding-standards#191]
In https://github.com/humanmade/coding-standards/pull/187#issuecomment-610105370 it was identified that we should likely not be setting the `testVersion` value by default as it cannot be updated.

> The `<config name="testVersion" value="7.1-" />` should also be project based as it is near impossible to overrule otherwise.

We should look at removing this for 1.0.0 with the other ruleset-default breaking changes.

**Comment by ocean90** [comment]
Related upstream issue: https://github.com/squizlabs/PHP_CodeSniffer/issues/2197

**Comment by kadamwhite** [comment]
Cross-referencing #186, and this suggests that we remove the minimum in our base HM standards (as it cannot easily be overridden).
