### ISSUE TITLE
Bump eslint-plugin-react to > 7.14.0

### ISSUE THREAD

**Issue by mikeselander** [humanmade/coding-standards#194]
We added the `jsx-curly-newline` rule in 0.8.0, but our linter only pulls in 7.11 of `eslint-plugin-react`. However, that rule was [added in 7.14](https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.14.0). We need to bump this version and we likely need to release an 0.8.1 version because the linter bot will throw a load of errors.

**Comment by kadamwhite** [comment]
Needs to go out prior to the 1.0 bump
