### ISSUE TITLE
Directory name with `-` throws error HM.Files.NamespaceDirectoryName.NameMismatch

### ISSUE THREAD

**Issue by Nikschavan** [humanmade/coding-standards#205]
Example code snippet ([link](https://make.hmn.md/lint-check/#eyJmaWxlbmFtZSI6ImluYy9mb2xkZXItbmFtZS9uYW1lc3BhY2UucGhwIiwidHlwZSI6bnVsbCwiY29kZSI6Ijw/cGhwXG5cbm5hbWVzcGFjZSBGb29cXEJhclxcRm9sZGVyX05hbWU7XG4iLCJ2ZXJzaW9uIjoibGF0ZXN0In0=
))

This is fixed if the directory name has an `_` ([example snippet](https://make.hmn.md/lint-check/#eyJmaWxlbmFtZSI6ImluYy9mb2xkZXJfbmFtZS9uYW1lc3BhY2UucGhwIiwidHlwZSI6bnVsbCwiY29kZSI6Ijw/cGhwXG5cbm5hbWVzcGFjZSBGb29cXEJhclxcRm9sZGVyX05hbWU7XG4iLCJ2ZXJzaW9uIjoibGF0ZXN0In0=))

If folder names are recommended to have `_` instead of `-` then the error message should clarify that as it is confusing when it says `use folder_name instead` if it means to use this as a directory name.

Also, want to get clarification if `_` is recommended for directory names over `-`?

**Comment by mikeselander** [comment]
This was fixed in #99 and will be available after we release 1.0
