### ISSUE TITLE
Support array shapes, avoid conflicts with "Parameter comment must end with a full stop"

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/coding-standards#207]
We have several projects that use a (I believe non-standard) syntax like this for declaring members of an array:

```
 * @param array  $options {
 *     @type string   $build_path    Absolute file system path to the static asset output folder.
 *                                   Optional; defaults to the manifest file's parent folder.
 *     @type string   $handle        The handle to use when enqueuing the style/script bundle.
 *                                   Optional; defaults to the basename of the build folder's parent folder.
 *     @type array    $scripts       Script dependencies. Optional.
 *     @type array    $styles        Style dependencies. Optional.
 * }
```
This gets flagged on the end "}" line for "Parameter comment must end with a full stop".

Psalm and PHPStan alternatively appears to support this syntax
```
 * @return array{
 *   optional?: string,
 *   bar: int
 * }
```
which would trigger the same behavior.

So, this is a two-parter. (A) should we support a syntax like this (I think they are very useful, personally), and (B) should we disable the specific ParamCommentFullStop rule in order to avoid precluding verbose array parameter documentation.

**Comment by rmccue** [comment]
ping @joehoyle who's been working on building out Psalm stuff as well

The syntax we have is from WP's phpDoc standards, so if we switch, we should ensure we document that it's inconsistent.

> disable the specific ParamCommentFullStop rule in order to avoid precluding verbose array parameter documentation

Is this the "comment must end with a full stop" rule? If so, yes please, that rule has added no value imo.

**Comment by joehoyle** [comment]
I think Psalm's syntax is a _lot_ better for defining types, but it doesn't provide a way to add descriptions to types. I don't know if any type-inferring tooling reads WP's style, so they are mostly just useful for human docs, whereas Psalm is about also providing the information to the typechecker. 

If we did switch, I think there's also value is making `@param array` banned, and force declarations on all arrays. "Type array" is actually pretty useless, `array<int>`, `array{0: string, 1: int}` are useful though.

**Comment by rmccue** [comment]
I think the descriptions for this style, at least in TypeScript land, usually are a comment on the line above (similar to properties):

```ts
type Foo = {
    // This describes the `some` property.
    some?: value;

    /** Or maybe an inline doc comment */
    bar: Quux;
};
```

For Psalm, we could do similar, but I don't know if Psalm itself parses that, and how would we indicate it without nesting comments? Could end up with something like:

```php
/**
 * @return array{
 *     // Optional docs?
 *     optional?: string,
 *
 *     /** Or this???? Would break on close: */
 *     bar: int
 * }
 */
```

Is there a Psalm issue for this maybe? 🤔

**Comment by joehoyle** [comment]
FYI Psalm doesn't support that (yet!) https://psalm.dev/r/76ea74605a

**Comment by rmccue** [comment]
Filed https://github.com/vimeo/psalm/issues/3787 to see what the thoughts there are.

**Comment by mikeselander** [comment]
> Is this the "comment must end with a full stop" rule? If so, yes please, that rule has added no value imo.

I do appreciate the consistency that this rule adds, but it is a massive noise generator and I'd be comfortable with dropping it.

**Comment by kadamwhite** [comment]
Param comment full stop has been removed as of #175 , this should no longer be an issue.
