### ISSUE TITLE
jsdoc/require-jsdoc has been deprecated

### ISSUE THREAD

**Issue by kirstyburgoine** [humanmade/coding-standards#230]
## Description
While installing HM Coding Standards on the HM Playbook I kept getting this error:
```
error  Missing JSDoc comment  jsdoc/require-jsdoc
```

Looking at the ESLint docs, I discovered that this rule was deprecated in ESLint v5.10.0: https://eslint.org/docs/rules/require-jsdoc

I can see from my package.json that eslint is using 5.16.0 or above though, but it is still declared here: https://github.com/humanmade/coding-standards/blob/343c98c2ec29bed2425e007811a8a68a4a693bb7/packages/eslint-config-humanmade/index.js#L124-L131

So I'm guessing this either needs removing or updating to lint doc blocks slightly differently?

**Comment by pdewouters** [comment]
Yes this was noted on the original proposal. not sure why we added it https://github.com/humanmade/coding-standards/issues/157#issuecomment-567540662

**Comment by tfrommen** [comment]
@kirstyburgoine the rule that has been deprecated is the `require-jsdoc` ESLint core rule. In our coding standards, however, we are using the `jsdoc/require-jsdoc` rule that is included in `eslint-plugin-jsdoc`. So I think we are all good here...?

Can you link me to a PR/commit where you think something has been flagged incorrectly?

**Comment by ntwb** [comment]
> @kirstyburgoine the rule that has been deprecated is the `require-jsdoc` ESLint core rule. In our coding standards, however, we are using the `jsdoc/require-jsdoc` rule that is included in `eslint-plugin-jsdoc`. So I think we are all good here...?

Agreed, this is related to the `jsdoc/require-jsdoc` _plugin_ and not the deprecated `require-jsdoc` ESLint core rule.

Hence, JSDocs are required by HMCS or the rule can be disabled in a project
