### ISSUE TITLE
Replace deprecated declaration-property-unit-* rules

### ISSUE THREAD

**Issue by tfrommen** [humanmade/coding-standards#231]
The `declaration-property-unit-blacklist` and the `declaration-property-unit-whitelist` rules have been deprecated, and should be replaced with `declaration-property-unit-disallowed-list` and `declaration-property-unit-allowed-list`, respectively.

This will be a **breaking** change, as user overrides won't work any longer, and therefore require a **major** version release.

**References:**
* https://github.com/stylelint/stylelint/blob/13.7.0/lib/rules/declaration-property-unit-blacklist/README.md
* https://github.com/stylelint/stylelint/blob/13.7.0/lib/rules/declaration-property-unit-whitelist/README.md

**Comment by tfrommen** [comment]
This is actioned in #248.

**Comment by ntwb** [comment]
This is now fixed via #248 & #275
