### ISSUE TITLE
Package deprecations

### ISSUE THREAD

**Issue by tomjn** [humanmade/coding-standards#274]
```
npm WARN deprecated @stylelint/postcss-markdown@0.36.2: Use the original unforked package instead: postcss-markdown
npm WARN deprecated stylelint-config-wordpress@16.0.0: This package has been deprecated, please use @wordpress/stylelint-config or @wordpress/scripts
```

There may be others, I believe we can fix this by moving from v18 to v20 of `@wordpress/stylelint-config`:

https://github.com/humanmade/coding-standards/blob/master/packages/stylelint-config/package.json#L30

This should eliminate some deprecated package warnings in dependent projects

**Comment by ntwb** [comment]
This should now be resolved with #275 merged, closing this, new version will be published shortly
