### ISSUE TITLE
link

### ISSUE THREAD

**Issue by colomet** [humanmade/coding-standards#6]
http://engineering.hmn.md/style/ do not work. Instead http://engineering.hmn.md/

**Comment by jazzsequence** [comment]
It's moved to https://engineering.hmn.md/how-we-work/style/php/

**Comment by jazzsequence** [comment]
@colomet where are you seeing the other link? the readme.md has a working link.

**Comment by colomet** [comment]
![captura de pantalla 2017-05-02 a las 17 55 39](https://cloud.githubusercontent.com/assets/3929177/25626695/9e753174-2f60-11e7-9c11-dd8f22545e49.png)

**Comment by jazzsequence** [comment]
👍  Thanks!

**Comment by jazzsequence** [comment]
fixed
