### ISSUE TITLE
Alignment with equals signs

### ISSUE THREAD

**Issue by joehoyle** [humanmade/coding-standards#61]
There's seems to be a new part of `WordPress.Arrays.MultipleStatementAlignment.NotSameWarning` that makes the following a failure:

```php
$all['read_applications'] = true;
$all['read_application'] = true;
```

Do we want this / is this intentional? This is pretty dumb I think in most situations and probably leads to be putting lots of daniel spacing everywhere so the lines are not consecutive.

**Comment by rmccue** [comment]
👍 for removing this.

**Comment by mikeselander** [comment]
Looks like #96 cleared this out
