### ISSUE TITLE
ESLint --fix incorrectly formatting single line objects 

### ISSUE THREAD

**Issue by mattheu** [humanmade/coding-standards#63]
If I run `eslint --fix`, the following code...

```
{ foo: 1, bar: 2 },
```

is converted into this.

```
{ 
    foo: 1, bar: 2,
},
```

I don't think we should allow this.

In this case I would expect this:

```
{ 
    foo: 1, 
    bar: 2,
},
```

**Comment by kadamwhite** [comment]
Possibly resolved, test in latest standards

**Comment by mikeselander** [comment]
I've verified locally that this now works as expected.
