### ISSUE TITLE
Allow PHP7 function import syntax

### ISSUE THREAD

**Issue by pdewouters** [humanmade/coding-standards#66]
The following causes a warning: "There must be one USE keyword per declaration"

`use function NewsUK\HomepageCustomiser\{get_layout_id_for_term,get_preview_script_url,get_preview_style_url,is_enabled_for_term};`

This syntax is similar to how we write `import` statements in JS, so would make sense to allow

**Comment by tfrommen** [comment]
Fixed with 5d3de4f341815c62b0f7bcce477738ba3c77b074 (see #78).
