### ISSUE TITLE
Unexpected console statement.

### ISSUE THREAD

**Issue by joehoyle** [humanmade/coding-standards#68]
It seems `console.error` causes a eslint warning. Is this intentional? Is doing console.error / console.warn not a valid thing to do in production code?

**Comment by rmccue** [comment]
This is intentional, yeah. It has some performance issues, and it’s considered bad behaviour to reveal internal behaviour to users; we also ban `var_dump` in production even if it’s in HTML comments or similar.

If you really want to do this, you can always ignore the rule for that specific line.

**Comment by joehoyle** [comment]
👍
