### ISSUE TITLE
PHPUnit failing on master branch

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/coding-standards#73]
There are currently errors on the master branch when running PHPUnit. This blocks the merge of any new PR's, as the merge button is flagged to only accept passing Travis runs. I'm opening this issue to track resolving these failures.

<details><summary>Click to expand PHPUnit error output</summary>
<code><pre>
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

.......FFF.                                                       11 / 11 (100%)

Time: 140 ms, Memory: 12.00MB

There were 3 failures:

1) HM\CodingStandards\Tests\FixtureTests::test_passing_files with data set #1 ('/hm/gh/coding-standards/tests...er.php')
File /fixtures/pass/use-order.php should not contain any errors
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
+    11 => Array (...)
+    15 => Array (...)
+    19 => Array (...)
+    23 => Array (...)
+    27 => Array (...)
+    31 => Array (...)
+    35 => Array (...)
+    39 => Array (...)
+    43 => Array (...)
 )

/hm/gh/coding-standards/tests/FixtureTests.php:69

2) HM\CodingStandards\Tests\FixtureTests::test_passing_files with data set #2 ('/hm/gh/coding-standards/tests...ce.php')
File /fixtures/pass/inc/namespace.php should not contain any errors
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
+    11 => Array (...)
+    13 => Array (...)
+    14 => Array (...)
+    15 => Array (...)
+    16 => Array (...)
+    18 => Array (...)
+    19 => Array (...)
+    21 => Array (...)
+    28 => Array (...)
+    30 => Array (...)
+    31 => Array (...)
+    32 => Array (...)
+    33 => Array (...)
 )

/hm/gh/coding-standards/tests/FixtureTests.php:69

3) HM\CodingStandards\Tests\FixtureTests::test_failing_files with data set #0 ('/hm/gh/coding-standards/tests...er.php')
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     1 => Array (...)
+    10 => Array (...)
+    16 => Array (...)
 )

/hm/gh/coding-standards/tests/FixtureTests.php:118

FAILURES!
Tests: 11, Assertions: 8, Failures: 3.
</pre></code>
</details>

Tested on Travis in #72 and locally with PHP 7.2.7

**Comment by mikeselander** [comment]
This appears to have been resolved as tests are passing on master. Are you comfortable with closing this @kadamwhite?

**Comment by kadamwhite** [comment]
Aye!
