### ISSUE TITLE
Add PHPCompatibility rules for PHP 7.2

### ISSUE THREAD

**Issue by rmccue** [humanmade/coding-standards#74]
We should include the rules from [PHPCompatibility](https://github.com/PHPCompatibility/PHPCompatibility) for PHP 7.2 in the base set of rules, to ensure all greenfields code is compatible for when we roll it out to servers.

**Comment by rmccue** [comment]
Specifically, [the WP rules](https://github.com/PHPCompatibility/PHPCompatibilityWP).

**Comment by rmccue** [comment]
@tfrommen Do you have any specific code for this you can PR? 🙏

**Comment by tfrommen** [comment]
Now I do, see #81. 🙂
