### ISSUE TITLE
Don't require wp_parse_url instead of parse_url?

### ISSUE THREAD

**Issue by paulgibbs** [humanmade/coding-standards#83]
This is done, because, I quote:

>  * A wrapper for PHP's parse_url() function that handles consistency in the return
>   * values across PHP versions.
>   *
>   * PHP 5.4.7 expanded parse_url()'s ability to handle non-absolute url's, including
>   * schemeless and relative url's with :// in the path. This function works around
>   * those limitations providing a standard output on PHP 5.2~5.4+.
>   *
>   * Secondly, across various PHP versions, schemeless URLs starting containing a ":"
>   * in the query are being handled inconsistently. This function works around those
>   * differences as well.
>   *
>   * Error suppression is used as prior to PHP 5.3.3, an E_WARNING would be generated
>   * when URL parsing failed.

As far as I can tell, `parse_url()` is safe to use if you know your environment is going to be PHP >= 7.0. Does this project have a minimum supported PHP version? If it does, and it matches this constraint, can we please consider adding a rule exclude for `WordPress.WP.AlternativeFunctions.parse_url_parse_url` thank you

**Comment by rmccue** [comment]
👍 Added in #180. https://github.com/humanmade/coding-standards/pull/180/files#diff-5b1601ac858de17c83da280d3edbbf23R90
