### ISSUE TITLE
Split standard into core and style

### ISSUE THREAD

**Issue by rmccue** [humanmade/coding-standards#85]
In order to better assess third-party code, we should split out the core (security, performance) rules from the style rules. We should do this for both PHP and JS, but PHP is a larger priority.

**Comment by kadamwhite** [comment]
This is complete for PHP following #180 ! :tada: :confetti_ball: 

JS and CSS would both benefit from this treatment, but after discussion with @rmccue that's a lower priority and we can open new issues to track those backlog items in the future. Closing this out for 1.0.
