### ISSUE TITLE
Support [namespace].php too in file naming convention

### ISSUE THREAD

**Issue by joehoyle** [humanmade/coding-standards#89]
I think I might have seen this proposal somewhere before, but I can't find it here. Instead of requiring `my_namespace/namespace.php` where your namespace doesn't have any classes, we should support `my_namespace.php` so there's a little less folder cruft.

**Comment by mikeselander** [comment]
Related is: https://github.com/humanmade/Engineering/issues/83

**Comment by rmccue** [comment]
Merged in https://github.com/humanmade/Engineering/pull/112 so we need to update our rule here.
