### ISSUE TITLE
Reorganise readme.md structure

### ISSUE THREAD

**Issue by fklein-lu** [humanmade/coding-standards#91]
The readme structure could be improved, by regrouping content.

I propose the following:
1. Intro paragraph
2. Setup
3. Contributing (former _Testing_). Located towards the top to encourage people to contribute.
4. Using PHPUnit (extend, ignore, how to find out which sniffs fail,...).
5. Using ESlint (same as above).

I'm unsure about the _Included Checks_  section, because it could be interpreted as providing more background about the sniffs, or be considered a shout out section. We could integrate and extend this content based on what the goal is.

Let's discuss structure first, happy to follow up with a PR once we have settled on an outline.

**Comment by mikeselander** [comment]
I think that this was well-covered in #178 - feel free to open another issue if anyone feels we could better clarify!
