### ISSUE TITLE
Ignore `inc` namespace rule in test directories

### ISSUE THREAD

**Issue by mikeselander** [humanmade/coding-standards#92]
The `NamespaceDirectoryNameSniff` sniff currently requires namespaces within test directory files, but this should not be required as test files are outside of a plugin-based organizational structure.

Should check for `/.test` and `/test` directories in path and if found, bypass this rule.

**Comment by rmccue** [comment]
Let’s pick one of these rather than both. I think the handbook has `tests/`?

**Comment by mikeselander** [comment]
`/tests` it is 👍 We'll need to adapt `hm-base` as well, but I'm happy to handle that.
