### ISSUE TITLE
Invalid configuration for object-curly-newline

### ISSUE THREAD

**Issue by pdewouters** [humanmade/coding-standards#95]
We have installed the composer package in a WP plugin, this plugin has a `package.json` file with a dependency of `react-scripts` - v2.0.4.
The composer package has a dependency on `0.5.0` of this library.

When running `eslint` from the root of the plugin, we get the following error:
```
/Users/daniel-westall/sites/hmn.newsuk/vvv/www/wordpress-default/public_html/wp-content/plugins/nu-sun-web-wp-home-page-customiser-V2/vendor/humanmade/coding-standards/packages/eslint-config-humanmade/index.js:
    Configuration for rule "object-curly-newline" is invalid:
    Value "[object Object]" should be equal to one of the allowed values.
    Value "[object Object]" should NOT have additional properties.
    Value "[object Object]" should match exactly one schema in oneOf.
    Value "[object Object]" should NOT have additional properties.
    Value "[object Object]" should match exactly one schema in oneOf.
```

This version of `react-script` uses `eslint` v5. I couldn't find anything related to this rule specifically in the release notes 
I'm guessing either the new version has some backward incompatible change that I haven't found, or there's something broken in the config of the plugin.

Also 
```
[REACT] ./src/components/ItemClipboard.js
[REACT]   Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
```
This rule seems to be disabled in our coding standards, so that shouldn't be happening

**Comment by kadamwhite** [comment]
Need to refresh this to see if it's still an issue; may relate to #172 or #171

**Comment by mikeselander** [comment]
I could not re-produce this issue, please re-open if this crops up again.
